const ALL_COUNTRIES = 'ALL_COUNTRIES'
const COVID_INFO = 'COVID_INFO'
const LOADING_COVID_INFO= 'LOADING_COVID_INFO'
const ERROR_COVID_INFO= 'ERROR_COVID_INFO'
const COVID_INFO_GLOBALLY = 'COVID_INFO_GLOBALLY'
const LOADING_COVID_INFO_GLOBALLY = 'LOADING_COVID_INFO_GLOBALLY'
const ERROR_COVID_INFO_GLOBALLY = 'ERROR_COVID_INFO_GLOBALLY'
const LOADING_COUNTRIES = 'LOADING_COUNTRIES'
const ERROR_COUNTRIES = 'LOADING_COUNTRIES'

export {
  ALL_COUNTRIES,
  COVID_INFO,
  COVID_INFO_GLOBALLY,
  LOADING_COVID_INFO,
  ERROR_COVID_INFO,
  LOADING_COVID_INFO_GLOBALLY,
  ERROR_COVID_INFO_GLOBALLY,
  LOADING_COUNTRIES,
  ERROR_COUNTRIES
}